#!/usr/bin/env bash

out=$(python ../main.py)
exit_status=$?
if [ $exit_status -eq 1 ]; then
  echo '{"id": "python-unit-test", "event": "on_new_changeset", "output": "${out}", "score": -1}'
else
  echo '{"id": "python-unit-test", "event": "on_new_changeset", "output": "${out}", "score": 1}'
fi
